INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Sillin', 'Marco','com.sofactory.entidades.Sillin');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Canguro', 'Marco','com.sofactory.entidades.Canguro');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('GuardabarroTrasero', 'Marco','com.sofactory.entidades.GuardabarroTrasero');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Marco','com.sofactory.entidades.Marco');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Fijo', 'Suspension','com.sofactory.entidades.Fijo');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Amortiguador', 'Suspension','com.sofactory.entidades.Amortiguador');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Suspension', 'Tenedor','com.sofactory.entidades.Suspension');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('GuardabarroDelantero', 'Tenedor','com.sofactory.entidades.GuardabarroDelantero');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Tenedor','com.sofactory.entidades.Tenedor');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Manubrio','com.sofactory.entidades.Manubrio');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Disco', 'Freno','com.sofactory.entidades.Disco');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Banda', 'Freno','com.sofactory.entidades.Banda');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Freno','com.sofactory.entidades.Freno');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Llanta','com.sofactory.entidades.Llanta');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('PlatoPinon', 'Traccion','com.sofactory.entidades.PlatoPinon');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Cambios', 'Traccion','com.sofactory.entidades.Cambios');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Cadena','com.sofactory.entidades.Cadena');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Calapie', 'Pedal','com.sofactory.entidades.Calapie');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Pedal','com.sofactory.entidades.Pedal');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Reflector', 'Accesorios','com.sofactory.entidades.Reflector');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('CadenaAntirobo', 'Accesorios','com.sofactory.entidades.CadenaAntirobo');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Parrilla', 'Accesorios','com.sofactory.entidades.Parrilla');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`, `NOMBRE_PADRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Canasta', 'Accesorios','com.sofactory.entidades.Canasta');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Accesorios','com.sofactory.entidades.Accesorio');
INSERT INTO `capitalcycles`.`cb_listado_partes` (`NOMBRE_FEATURE`,`NOMBRE_CLASE_PARTE`) VALUES ('Traccion','com.sofactory.entidades.Traccion');

INSERT INTO `capitalcycles`.`cb_especificacion` (`COLOR`, `MARCA`, `PRECIO`) VALUES ('Azul', 'Trek', '2500');
INSERT INTO `capitalcycles`.`cb_especificacion` (`COLOR`, `MARCA`, `PRECIO`) VALUES ('Verde', 'Specialized', '2000');
INSERT INTO `capitalcycles`.`cb_especificacion` (`COLOR`, `MARCA`, `PRECIO`) VALUES ('Gris', 'Orbea', '3000');
INSERT INTO `capitalcycles`.`cb_especificacion` (`COLOR`, `MARCA`, `PRECIO`) VALUES ('Negro', 'Bianchi', '15000');
INSERT INTO `capitalcycles`.`cb_especificacion` (`COLOR`, `MARCA`, `PRECIO`) VALUES ('Cafe', 'Felt', '10000');

INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (1,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (2,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (3,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (4,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (5,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (6,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (7,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (8,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (9,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (10,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (11,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (12,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (13,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (14,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (15,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (16,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (17,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (18,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (19,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (20,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (21,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (22,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (23,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (24,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (25,1);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (1,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (2,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (3,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (4,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (5,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (6,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (7,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (8,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (9,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (10,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (11,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (12,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (13,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (14,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (15,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (16,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (17,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (18,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (19,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (20,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (21,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (22,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (23,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (24,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (25,2);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (1,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (2,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (3,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (4,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (5,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (6,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (7,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (8,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (9,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (10,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (11,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (12,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (13,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (14,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (15,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (16,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (17,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (18,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (19,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (20,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (21,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (22,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (23,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (24,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (25,3);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (1,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (2,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (3,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (4,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (5,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (6,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (7,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (8,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (9,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (10,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (11,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (12,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (13,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (14,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (15,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (16,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (17,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (18,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (19,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (20,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (21,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (22,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (23,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (24,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (25,4);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (1,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (2,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (3,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (4,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (5,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (6,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (7,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (8,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (9,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (10,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (11,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (12,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (13,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (14,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (15,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (16,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (17,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (18,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (19,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (20,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (21,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (22,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (23,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (24,5);
INSERT INTO cb_listado_partes_especificacion (CODIGO_LISTADO_PARTES,CODIGO_ESPECIFICACION) VALUES (25,5);